services:
  #nginx
  web: 
    image: nginx:latest
    ports:
      - "1080:80"
  
  app:
    build:
      dockerfile: ./php/Dockerfile
        

  #php
  #mysql
  #redis


  # commands:
  # 1. docker ps | docker compose ps
  # 2. docker compose up
  # 3. docker build -t omerfarooq:php81 -f php/Dockerfile . ## This will build the image using Dockerfile