services:
  #nginx
  web: 
    image: nginx:latest
    ports:
      - "1080:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  
  app:
    build:
      dockerfile: ./php/Dockerfile
    volumes:
      - ./app:/app

  #php
  #mysql
  #redis


  # commands:
  # 1. docker ps | docker compose ps
  # 2. docker compose up -d
  # 3. docker build -t omerfarooq:php81 -f php/Dockerfile . ## This will build the image using Dockerfile
  # 4. docker images ## shows the built images
  # 5. docker exec -it [container] sh ## logs into the container shell