services:
  #nginx
  web: 
    image: nginx:latest
    ports:
      - "1080:80"
  
  app:
    build:
      dockerfile: ./php/Dockerfile
        

  #php
  #mysql
  #redis


  # commands:
  # 1. Docker ps | Docker compose ps
  # 2. Docker compose up